/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SurfaceOptions.java
 *
 * Created on Nov 25, 2009, 8:52:04 AM
 */
package tensor.view;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.AbstractCellEditor;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JColorChooser;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import projection3d.surface.SurfaceFactory;
import projection3d.surface.SurfaceFactory.SurfaceType;
import tensor.model.FiberInstance;
import tensor.model.FiberModel;
import visualizationbasics.model.AbstractInstance;
import vtk.vtkSurfaceActor;

/**
 *
 * @author jpocom
 */
public class SurfaceOptions extends javax.swing.JDialog {

    /** Creates new form SurfaceOptions */
    public SurfaceOptions(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        surfaceTableModel = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int col) {
                if (col == 0) {
                    return false;
                }
                return true;
            }
        };
        surfaceTableModel.addColumn("Name");
        surfaceTableModel.addColumn("Opacity");
        surfaceTableModel.addColumn("Visible");
        surfaceTableModel.addColumn("Color");

        initComponents();
        
        surfaceTable.setRowHeight(30);

        surfaceTable.getColumnModel().getColumn(0).setPreferredWidth(50);

        surfaceTable.getColumnModel().getColumn(1).setCellEditor(new JSliderEditor());
        surfaceTable.getColumnModel().getColumn(1).setCellRenderer(new JSliderRenderer());

        surfaceTable.getColumnModel().getColumn(2).setCellEditor(new CheckBoxCellEditor());
        surfaceTable.getColumnModel().getColumn(2).setCellRenderer(new CWCheckBoxRenderer());

        surfaceTable.getColumnModel().getColumn(3).setCellEditor(new ColorEditor());
        surfaceTable.getColumnModel().getColumn(3).setCellRenderer(new ColorRenderer(true));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablePopupMenu = new javax.swing.JPopupMenu();
        surfacesHide = new javax.swing.JMenuItem();
        surfacesShow = new javax.swing.JMenuItem();
        separator1 = new javax.swing.JSeparator();
        surfacesDelete = new javax.swing.JMenuItem();
        surfacesJoin = new javax.swing.JMenuItem();
        separator2 = new javax.swing.JSeparator();
        surfacesSave = new javax.swing.JMenuItem();
        tableScrollPane = new javax.swing.JScrollPane();
        surfaceTable = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        surfacesHide.setText("Hide Surface");
        surfacesHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surfacesHideActionPerformed(evt);
            }
        });
        tablePopupMenu.add(surfacesHide);

        surfacesShow.setText("Show Surfaces");
        surfacesShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surfacesShowActionPerformed(evt);
            }
        });
        tablePopupMenu.add(surfacesShow);
        tablePopupMenu.add(separator1);

        surfacesDelete.setText("Delete Surfaces");
        surfacesDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surfacesDeleteActionPerformed(evt);
            }
        });
        tablePopupMenu.add(surfacesDelete);

        surfacesJoin.setText("Join Surfaces");
        surfacesJoin.setToolTipText("Create a new Surfaces using points in selected surfaces");
        surfacesJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surfacesJoinActionPerformed(evt);
            }
        });
        tablePopupMenu.add(surfacesJoin);
        tablePopupMenu.add(separator2);

        surfacesSave.setText("Save Projection");
        surfacesSave.setToolTipText("Save instances in selected surfaces as XML");
        surfacesSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surfacesSaveActionPerformed(evt);
            }
        });
        tablePopupMenu.add(surfacesSave);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableScrollPane.setPreferredSize(new java.awt.Dimension(450, 200));

        surfaceTable.setModel(surfaceTableModel);
        surfaceTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        surfaceTable.setComponentPopupMenu(tablePopupMenu);
        surfaceTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tableScrollPane.setViewportView(surfaceTable);

        getContentPane().add(tableScrollPane, java.awt.BorderLayout.CENTER);

        buttonPanel.setPreferredSize(new java.awt.Dimension(400, 33));

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(closeButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.frame = null;
        this.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void surfacesDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surfacesDeleteActionPerformed
        if (frame != null) {
            ArrayList<vtkSurfaceActor> acts = new ArrayList<vtkSurfaceActor>();
            for (int row : surfaceTable.getSelectedRows()) {
                vtkSurfaceActor act = (vtkSurfaceActor) surfaceTableModel.getValueAt(row, 0);
                acts.add(act);
            }
            model.removeSurfaces(frame.getView().GetRenderer(), acts);
            selectedSurfs.removeAll(acts);

            updateTable();
            frame.getView().repaint();
        }
    }//GEN-LAST:event_surfacesDeleteActionPerformed

    private void surfacesJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surfacesJoinActionPerformed
        if (model != null) {
            ArrayList<AbstractInstance> instances = new ArrayList<AbstractInstance>();
            for (int row : surfaceTable.getSelectedRows()) {
                vtkSurfaceActor act = (vtkSurfaceActor) surfaceTableModel.getValueAt(row, 0);
                instances.addAll(act.getInstances());
            }
            int totalNumberPoints = 0;
            for (AbstractInstance inst : instances) {
                totalNumberPoints += ((FiberInstance) inst).getNumberOfPoints();
            }

            double[] color = new double[3];
            double[][] ptrs = new double[totalNumberPoints][3];
            int pos = 0;
            for (AbstractInstance inst : instances) {
                FiberInstance fiber = (FiberInstance) inst;
                for (int i = 0; i < fiber.getNumberOfPoints(); i++) {
                    double[] point = fiber.getPointDouble(i);
                    ptrs[pos][0] = point[0];
                    ptrs[pos][1] = point[1];
                    ptrs[pos++][2] = point[2];
                }
                color[0] += fiber.getColor().getRed();
                color[1] += fiber.getColor().getGreen();
                color[2] += fiber.getColor().getBlue();
            }
            color[0] /= instances.size() * 256.;
            color[1] /= instances.size() * 256.;
            color[2] /= instances.size() * 256.;

            vtkSurfaceActor act = SurfaceFactory.getInstance(SurfaceType.DENSITY, ptrs, "");
            act.setInstances(instances);
            act.GetProperty().SetColor(color);
            
            model.addSurface(act);
            selectedSurfs.add(act);

            updateTable();
            frame.getView().repaint();
        }
    }//GEN-LAST:event_surfacesJoinActionPerformed

    private void surfacesSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surfacesSaveActionPerformed
        /*
        if (frame != null) {
        try {
        Projection3DModel model = (Projection3DModel) frame.getModel();

        Projection3DModel m = new Projection3DModel(TypeGlyph.POINT);
        for(Scalar s: model.getScalars()) {
        m.addScalar(s.getName());
        }
        for (int row : surfaceTable.getSelectedRows()) {
        vtkSurfaceActor actor = (vtkSurfaceActor)((Topic) surfaceTableModel.getValueAt(row, 0)).getActor();

        for (Projection3DInstance inst : actor.getInstances()) {
        m.addInstance(inst);
        }
        }

        XMLModel3DWriterComp comp = new XMLModel3DWriterComp();
        comp.input(m);
        Util.showDialog(comp);
        comp.execute();

        } catch (IOException ex) {
        Logger.getLogger(SurfaceOptions.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
         * */
    }//GEN-LAST:event_surfacesSaveActionPerformed

    private void surfacesHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surfacesHideActionPerformed
        if (model != null) {
            for (int row : surfaceTable.getSelectedRows()) {
                vtkSurfaceActor act = (vtkSurfaceActor) surfaceTableModel.getValueAt(row, 0);
                act.SetVisibility(0);
                frame.getView().repaint();
            }

            updateTable();
        }
    }//GEN-LAST:event_surfacesHideActionPerformed

    private void surfacesShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surfacesShowActionPerformed
        if (model != null) {
            for (int row : surfaceTable.getSelectedRows()) {
                vtkSurfaceActor act = (vtkSurfaceActor) surfaceTableModel.getValueAt(row, 0);
                act.SetVisibility(1);
                frame.getView().repaint();
            }

            updateTable();
        }
    }//GEN-LAST:event_surfacesShowActionPerformed
 
    public void updateTable() {
        while (surfaceTableModel.getRowCount() > 0) {
            surfaceTableModel.removeRow(0);
        }

        if (model != null) {
            for (vtkSurfaceActor act : selectedSurfs) {
                int opacity = (int) (act.GetProperty().GetOpacity() * 100.);
                boolean visibility = act.GetVisibility() == 1 ? true : false;
                double[] temp = act.GetProperty().GetColor();
                Color color = new Color((float)temp[0], (float) temp[1], (float) temp[2]);

                surfaceTableModel.addRow(new Object[]{act, opacity, visibility, color});
            }
        }
    }

    public static SurfaceOptions getInstance(javax.swing.JFrame parent) {
        return new SurfaceOptions(parent, false);
    }

    public void display(FibersFrame frame, ArrayList<vtkSurfaceActor> selectedSurfs) {
        if (frame != null) {
            this.frame = frame;
            this.model = (FiberModel) frame.getModel();
            this.selectedSurfs = selectedSurfs;

            if (model != null) {
                updateTable();
            }
        }

        setLocationRelativeTo(this.getParent());
        setVisible(true);
    }
    FibersFrame frame = null;
    FiberModel model = null;
    ArrayList<vtkSurfaceActor> selectedSurfs;
    DefaultTableModel surfaceTableModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JTable surfaceTable;
    private javax.swing.JMenuItem surfacesDelete;
    private javax.swing.JMenuItem surfacesHide;
    private javax.swing.JMenuItem surfacesJoin;
    private javax.swing.JMenuItem surfacesSave;
    private javax.swing.JMenuItem surfacesShow;
    private javax.swing.JPopupMenu tablePopupMenu;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables

    class JSliderEditor extends AbstractCellEditor implements TableCellEditor {

        protected JSlider slider = null;
        int row = -1;
        int col = -1;

        public JSliderEditor() {
            slider = new JSlider();

            this.slider.addMouseListener(new MouseAdapter() {

                @Override
                public void mouseReleased(MouseEvent evt) {
                    vtkSurfaceActor act = (vtkSurfaceActor) surfaceTableModel.getValueAt(row, 0);
                    act.GetProperty().SetOpacity(slider.getValue() / 100.0);
                    frame.getView().repaint();
                }
            });
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int col) {
            int val = Integer.parseInt(value.toString());
            slider.setValue(val);
            this.row = row;
            this.col = col;
            return slider;
        }

        @Override
        public Object getCellEditorValue() {
            return new Integer(slider.getValue());
        }
    }

    class JSliderRenderer implements TableCellRenderer {

        protected JSlider slider = null;

        public JSliderRenderer() {
            slider = new JSlider();
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            int val = Integer.parseInt(value.toString());
            slider.setValue(val);
            return slider;
        }
    }

    class CheckBoxCellEditor extends AbstractCellEditor implements TableCellEditor {

        protected JCheckBox checkBox;
        protected int row = -1;

        public CheckBoxCellEditor() {
            checkBox = new JCheckBox();
            checkBox.setHorizontalAlignment(SwingConstants.CENTER);
            checkBox.setBackground(Color.white);

            checkBox.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    vtkSurfaceActor act = (vtkSurfaceActor) surfaceTableModel.getValueAt(row, 0);
                    act.SetVisibility(checkBox.isSelected() == true ? 1 : 0);
                    frame.getView().repaint();
                }
            });
        }

        @Override
        public Component getTableCellEditorComponent(
                JTable table,
                Object value,
                boolean isSelected,
                int row,
                int column) {

            checkBox.setSelected(((Boolean) value).booleanValue());
            this.row = row;
            return checkBox;
        }

        @Override
        public Object getCellEditorValue() {
            return Boolean.valueOf(checkBox.isSelected());
        }
    }

    class CWCheckBoxRenderer extends JCheckBox implements TableCellRenderer {

        Border border = new EmptyBorder(1, 2, 1, 2);

        public CWCheckBoxRenderer() {
            super();
            setOpaque(true);
            setHorizontalAlignment(SwingConstants.CENTER);
        }

        @Override
        public Component getTableCellRendererComponent(
                JTable table,
                Object value,
                boolean isSelected,
                boolean hasFocus,
                int row,
                int column) {

            if (value instanceof Boolean) {
                setSelected(((Boolean) value).booleanValue());
                setEnabled(table.isCellEditable(row, column));

                if (isSelected) {
                    setBackground(table.getSelectionBackground());
                    setForeground(table.getSelectionForeground());
                } else {
                    setForeground(table.getForeground());
                    setBackground(table.getBackground());
                }
            } else {
                return null;
            }

            return this;
        }
    }

    class ColorRenderer extends JLabel implements TableCellRenderer {

        Border unselectedBorder = null;
        Border selectedBorder = null;
        boolean isBordered = true;

        public ColorRenderer(boolean isBordered) {
            this.isBordered = isBordered;
            setOpaque(true); //MUST do this for background to show up.
        }

        @Override
        public Component getTableCellRendererComponent(
                JTable table, Object color,
                boolean isSelected, boolean hasFocus,
                int row, int column) {
            Color newColor = (Color) color;
            setBackground(newColor);
            if (isBordered) {
                if (isSelected) {
                    if (selectedBorder == null) {
                        selectedBorder = BorderFactory.createMatteBorder(2, 5, 2, 5,
                                table.getSelectionBackground());
                    }
                    setBorder(selectedBorder);
                } else {
                    if (unselectedBorder == null) {
                        unselectedBorder = BorderFactory.createMatteBorder(2, 5, 2, 5,
                                table.getBackground());
                    }
                    setBorder(unselectedBorder);
                }
            }

            setToolTipText("RGB value: " + newColor.getRed() + ", " + newColor.getGreen() + ", " + newColor.getBlue());
            return this;
        }
    }

    class ColorEditor extends AbstractCellEditor implements TableCellEditor,
            ActionListener {

        Color currentColor;
        JButton button;
        JColorChooser colorChooser;
        JDialog dialog;
        protected static final String EDIT = "edit";
        private int row = -1;

        public ColorEditor() {
            button = new JButton();
            button.setActionCommand(EDIT);
            button.addActionListener(this);
            button.setBorderPainted(false);

            //Set up the dialog that the button brings up.
            colorChooser = new JColorChooser();
            dialog = JColorChooser.createDialog(button,
                    "Pick a Color",
                    true, //modal
                    colorChooser,
                    this, //OK button handler
                    null); //no CANCEL button handler
        }

        /**
         * Handles events from the editor button and from
         * the dialog's OK button.
         */
        @Override
        public void actionPerformed(ActionEvent e) {
            if (EDIT.equals(e.getActionCommand())) {
                //The user has clicked the cell, so
                //bring up the dialog.
                button.setBackground(currentColor);
                colorChooser.setColor(currentColor);
                dialog.setVisible(true);

                //Make the renderer reappear.
                fireEditingStopped();

            } else { //User pressed dialog's "OK" button.
                currentColor = colorChooser.getColor();
                vtkSurfaceActor act = (vtkSurfaceActor) surfaceTableModel.getValueAt(row, 0);
                act.GetProperty().SetColor(currentColor.getRed() / 255., currentColor.getGreen() / 255., currentColor.getBlue() / 255.);
                frame.getView().repaint();
            }
        }

        //Implement the one CellEditor method that AbstractCellEditor doesn't.
        @Override
        public Object getCellEditorValue() {
            return currentColor;
        }

        //Implement the one method defined by TableCellEditor.
        @Override
        public Component getTableCellEditorComponent(JTable table,
                Object value,
                boolean isSelected,
                int row,
                int column) {
            currentColor = (Color) value;
            this.row = row;
            return button;
        }
    }
}
