/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BMPVolumeReaderParamView.java
 *
 * Created on 10/08/2009, 16:21:29
 */
package volume.model;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import vispipelinebasics.interfaces.AbstractParametersView;

/**
 *
 * @author Danilo Medeiros Eler
 */
public class BMPVolumeReaderParamView extends AbstractParametersView {

    /** Creates new form BMPVolumeReaderParamView */
    public BMPVolumeReaderParamView(BMPVolumeReaderComp comp) {
        initComponents();

        this.comp = comp;
        reset();
    }

    @Override
    public void reset() {
        //matrixTextField.setText(comp.getFilename());
        System.out.println("BMP reset");
    }

    @Override
    public void finished() throws IOException {
        System.out.println("BMP finished");
        if (dir_Text.getText().trim().length() > 0) {
            comp.setDirectory(dir_Text.getText());
        } else {
            throw new IOException("A directory must be provided.");
        }
        if (filePattern_Text.getText().trim().length() > 0) {
            comp.setFilepattern(filePattern_Text.getText());
        } else {
            throw new IOException("A file pattern must be provided.");
        }
        if (X_Text.getText().trim().length() > 0 &&
                Y_Text.getText().trim().length() > 0 &&
                Z_Text.getText().trim().length() > 0) {
            comp.setX(Integer.parseInt(X_Text.getText()));
            comp.setY(Integer.parseInt(Y_Text.getText()));
            comp.setZ(Integer.parseInt(Z_Text.getText()));
        } else {
            throw new IOException("A data spacing must be provided.");
        }
        if (X1_Text.getText().trim().length() > 0 &&
                Y1_Text.getText().trim().length() > 0 &&
                Z1_Text.getText().trim().length() > 0 &&
                X2_Text.getText().trim().length() > 0 &&
                Y2_Text.getText().trim().length() > 0 &&
                Z2_Text.getText().trim().length() > 0) {
            comp.setX1(Integer.parseInt(X1_Text.getText()));
            comp.setY1(Integer.parseInt(Y1_Text.getText()));
            comp.setZ1(Integer.parseInt(Z1_Text.getText()));
            comp.setX2(Integer.parseInt(X2_Text.getText()));
            comp.setY2(Integer.parseInt(Y2_Text.getText()));
            comp.setZ2(Integer.parseInt(Z2_Text.getText()));
        } else {
            throw new IOException("A data spacing must be provided.");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        dir_Text = new javax.swing.JTextField();
        findDir_JButton = new javax.swing.JButton();
        filePattern_jLabel = new javax.swing.JLabel();
        filePattern_Text = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        X_Text = new javax.swing.JTextField();
        Y_Text = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Z_Text = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        X1_Text = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        X2_Text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Y1_Text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Y2_Text = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Z1_Text = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Z2_Text = new javax.swing.JTextField();

        jLabel12.setText("Directory");

        dir_Text.setText("D:\\DANILO\\DOUTORADO\\VisContest08\\volume");

        findDir_JButton.setText("Find");
        findDir_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findDir_JButtonActionPerformed(evt);
            }
        });

        filePattern_jLabel.setText("File Pattern");

        filePattern_Text.setText("contest_%03i.bmp");

        jLabel11.setText("Data Spacing");

        X_Text.setText("1");
        X_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                X_TextActionPerformed(evt);
            }
        });

        Y_Text.setText("1");
        Y_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Y_TextActionPerformed(evt);
            }
        });

        jLabel8.setText("X");

        jLabel9.setText("Y");

        jLabel10.setText("Z");

        Z_Text.setText("1");
        Z_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Z_TextActionPerformed(evt);
            }
        });

        jLabel7.setText("Data Extent");

        X1_Text.setText("0");
        X1_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                X1_TextActionPerformed(evt);
            }
        });

        jLabel1.setText("X1");

        jLabel2.setText("X2");

        X2_Text.setText("149");

        jLabel3.setText("Y1");

        Y1_Text.setText("0");

        jLabel4.setText("Y2");

        Y2_Text.setText("61");

        jLabel5.setText("Z1");

        Z1_Text.setText("0");

        jLabel6.setText("Z2");

        Z2_Text.setText("61");
        Z2_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Z2_TextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filePattern_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(filePattern_jLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(X_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(Y_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(Z_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel11))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(findDir_JButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(X1_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(X2_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(Y1_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(Y2_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(Z1_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(Z2_Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel7))
                                .addGap(157, 157, 157))))
                    .addComponent(dir_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findDir_JButton)
                    .addComponent(dir_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filePattern_jLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filePattern_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(X_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Y_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Z_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(4, 4, 4)
                                        .addComponent(Y2_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(4, 4, 4)
                                        .addComponent(Y1_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(X2_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(X1_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Z1_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Z2_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(97, 97, 97))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void findDir_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findDir_JButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Volume Directory");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            this.dir_Text.setText(chooser.getSelectedFile().getAbsolutePath());
            fillVolumeInformation(this.dir_Text.getText());
        }
    }//GEN-LAST:event_findDir_JButtonActionPerformed

    public void fillVolumeInformation(String directory) {
        File dir = new File(directory);
        ArrayList<String> bmps = new ArrayList<String>();
        String[] files = dir.list();
        if (files.length > 0) {
            for (int i = 0; i < files.length; i++) {
                //System.out.println(files[i]);
                if (files[i].endsWith(".bmp")) {
                    //System.out.println("  - BMP file");
                    bmps.add(files[i]);
                }
            }
            if (bmps.size() > 0) {
                File f = new File(directory + "\\" + bmps.get(0));
                //System.out.println("\n\nVolume Information");
                try {
                    BufferedImage img = ImageIO.read(f);
                    this.filePattern_jLabel.setText("File Pattern (File: " + bmps.get(0) + ")");
                    //System.out.println("Width: " +img.getWidth());
                    this.X1_Text.setText("0");
                    this.X2_Text.setText(Integer.toString(img.getWidth() - 1));
                    //System.out.println("Height: " + img.getHeight());
                    this.Y1_Text.setText("0");
                    this.Y2_Text.setText(Integer.toString(img.getHeight() - 1));
                    //System.out.println("Slices: " + bmps.size());
                    this.Z1_Text.setText("0");
                    this.Z2_Text.setText(Integer.toString(bmps.size() - 1));
                } catch (java.io.IOException ie) {
                    ie.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(null, "No BMP file in this directory.");
            }

        } else {
            JOptionPane.showMessageDialog(null, "No file in this directory.");
        }
    }

    private void X_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X_TextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_X_TextActionPerformed

    private void Y_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Y_TextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_Y_TextActionPerformed

    private void Z_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Z_TextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_Z_TextActionPerformed

    private void X1_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X1_TextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_X1_TextActionPerformed

    private void Z2_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Z2_TextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_Z2_TextActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField X1_Text;
    private javax.swing.JTextField X2_Text;
    private javax.swing.JTextField X_Text;
    private javax.swing.JTextField Y1_Text;
    private javax.swing.JTextField Y2_Text;
    private javax.swing.JTextField Y_Text;
    private javax.swing.JTextField Z1_Text;
    private javax.swing.JTextField Z2_Text;
    private javax.swing.JTextField Z_Text;
    private javax.swing.JTextField dir_Text;
    private javax.swing.JTextField filePattern_Text;
    private javax.swing.JLabel filePattern_jLabel;
    private javax.swing.JButton findDir_JButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
    private BMPVolumeReaderComp comp;
}
