/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * XMLModelReaderParamView.java
 *
 * Created on 02/08/2009, 16:29:28
 */
package projection3d.model;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import projection3d.model.Projection3DModel.TypeGlyph;
import projection.util.ProjectionConstants;
import projection.util.filter.XMLFilter;
import projection.view.JExtendedComboBox;
import vispipelinebasics.interfaces.AbstractParametersView;
import visualizationbasics.util.OpenDialog;
import visualizationbasics.util.PropertiesManager;

/**
 *
 * @author Fernando V. Paulovic
 */
public class XMLModel3DReaderParamView extends AbstractParametersView {

    /** Creates new form XMLModelReaderParamView */
    public XMLModel3DReaderParamView(XMLModel3DReaderComp comp) {
        this.typeComboModel = new DefaultComboBoxModel();
        initComponents();

        this.comp = comp;
        reset();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        matrixLabel = new javax.swing.JLabel();
        matrixTextField = new javax.swing.JTextField();
        matrixButton = new javax.swing.JButton();
        typeLabel = new javax.swing.JLabel();
        typeCombo = new JExtendedComboBox(this.typeComboModel);

        setBorder(javax.swing.BorderFactory.createTitledBorder("XML Projection Model Reader"));
        setLayout(new java.awt.GridBagLayout());

        matrixLabel.setText("File name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(matrixLabel, gridBagConstraints);

        matrixTextField.setColumns(35);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(matrixTextField, gridBagConstraints);

        matrixButton.setText("Search...");
        matrixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrixButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(matrixButton, gridBagConstraints);

        typeLabel.setText("Instance Representation:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(typeLabel, gridBagConstraints);

        typeCombo.setPreferredSize(new java.awt.Dimension(120, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(typeCombo, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void matrixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrixButtonActionPerformed
        try {
            PropertiesManager spm = PropertiesManager.getInstance(ProjectionConstants.PROPFILENAME);
            int result = OpenDialog.showOpenDialog(spm, new XMLFilter(), this);

            if (result == JFileChooser.APPROVE_OPTION) {
                String filename = OpenDialog.getFilename();
                matrixTextField.setText(filename);
            }
        } catch (IOException ex) {
            Logger.getLogger(XMLModel3DReaderParamView.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_matrixButtonActionPerformed

    @Override
    public void reset() {
        typeComboModel.removeAllElements();

        for (TypeGlyph val: TypeGlyph.values()) {
            typeCombo.addItem(val);
        }

        typeCombo.setSelectedItem(comp.getTypeGlyph());

        matrixTextField.setText(comp.getFilename());
    }

    @Override
    public void finished() throws IOException {
        if (matrixTextField.getText().trim().length() > 0) {
            comp.setFilename(matrixTextField.getText());
        } else {
            throw new IOException("A matrix file name must be provided.");
        }
        comp.setTypeGlyph((TypeGlyph)typeComboModel.getSelectedItem());
    }

    private XMLModel3DReaderComp comp;
    private DefaultComboBoxModel typeComboModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton matrixButton;
    private javax.swing.JLabel matrixLabel;
    private javax.swing.JTextField matrixTextField;
    private javax.swing.JComboBox typeCombo;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
