/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FiberSamplingParamView.java
 *
 * Created on Nov 4, 2009, 3:07:17 AM
 */

package tensor.model;

import java.io.IOException;
import tensor.model.JoinMatrixesComp.TypeAppend;
import vispipelinebasics.interfaces.AbstractParametersView;

/**
 *
 * @author jpocom
 */
public class JoinMatrixesParamView extends AbstractParametersView {

    /** Creates new form FiberSamplingParamView */
    public JoinMatrixesParamView(JoinMatrixesComp comp) {
        initComponents();
        this.comp = comp;
        reset();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        nextRadioButton = new javax.swing.JRadioButton();
        underRadioButton = new javax.swing.JRadioButton();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("How to Join?"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        buttonGroup.add(nextRadioButton);
        nextRadioButton.setSelected(true);
        nextRadioButton.setText("B next to A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(nextRadioButton, gridBagConstraints);

        buttonGroup.add(underRadioButton);
        underRadioButton.setText("B under A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(underRadioButton, gridBagConstraints);

        add(jPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void finished() throws IOException {
        if (nextRadioButton.isSelected()) {
            comp.setType(TypeAppend.NEXT);
        } else {
            comp.setType(TypeAppend.UNDER);
        }
    }

    @Override
    public void reset() {
        if (comp.getType().equals(TypeAppend.NEXT)) {
            nextRadioButton.setSelected(true);
        } else {
            underRadioButton.setSelected(true);
        }
    }

    private JoinMatrixesComp comp;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton nextRadioButton;
    private javax.swing.JRadioButton underRadioButton;
    // End of variables declaration//GEN-END:variables

}
