/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProjClusProjectionParamView.java
 *
 * Created on 19/06/2009, 14:13:33
 */
package projection.technique.projclus;

import distance.dissimilarity.DissimilarityFactory.DissimilarityType;
import java.io.IOException;
import projection.technique.idmap.IDMAPProjection.InitializationType;
import vispipelinebasics.interfaces.AbstractParametersView;

/**
 *
 * @author Fernando Vieira Paulovich
 */
public class ProjClusProjectionParamView extends AbstractParametersView {

    /** Creates new form ProjClusProjectionParamView */
    public ProjClusProjectionParamView(ProjClusProjectionComp comp) {
        initComponents();

        this.comp = comp;

        for (DissimilarityType disstype : DissimilarityType.values()) {
            this.dissimilarityComboBox.addItem(disstype);
        }

        reset();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        projectorButtonGroup = new javax.swing.ButtonGroup();
        improvementPanel = new javax.swing.JPanel();
        nIterationsLabel = new javax.swing.JLabel();
        deltaLabel = new javax.swing.JLabel();
        deltaTextField = new javax.swing.JTextField();
        nIterationsTextField = new javax.swing.JTextField();
        clusterFactorLabel = new javax.swing.JLabel();
        clusterFactorTextField = new javax.swing.JTextField();
        projectionPanel = new javax.swing.JPanel();
        nnpRadioButton = new javax.swing.JRadioButton();
        fastmapRadioButton = new javax.swing.JRadioButton();
        dissimilarityPanel = new javax.swing.JPanel();
        dissimilarityComboBox = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("ProjClus Parameters"));
        setLayout(new java.awt.GridBagLayout());

        improvementPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Projection Improvement (Force)"));
        improvementPanel.setLayout(new java.awt.GridBagLayout());

        nIterationsLabel.setText("Number of iterations");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        improvementPanel.add(nIterationsLabel, gridBagConstraints);

        deltaLabel.setText("Fraction of delta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        improvementPanel.add(deltaLabel, gridBagConstraints);

        deltaTextField.setColumns(5);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        improvementPanel.add(deltaTextField, gridBagConstraints);

        nIterationsTextField.setColumns(5);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        improvementPanel.add(nIterationsTextField, gridBagConstraints);

        clusterFactorLabel.setText("Cluster Factor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        improvementPanel.add(clusterFactorLabel, gridBagConstraints);

        clusterFactorTextField.setColumns(5);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        improvementPanel.add(clusterFactorTextField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(improvementPanel, gridBagConstraints);

        projectionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Type of Projection"));
        projectionPanel.setLayout(new java.awt.GridBagLayout());

        projectorButtonGroup.add(nnpRadioButton);
        nnpRadioButton.setText("Nearest Neighbor Projection");
        nnpRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        nnpRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        projectionPanel.add(nnpRadioButton, gridBagConstraints);

        projectorButtonGroup.add(fastmapRadioButton);
        fastmapRadioButton.setText("Fastmap Projection");
        fastmapRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        fastmapRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        projectionPanel.add(fastmapRadioButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(projectionPanel, gridBagConstraints);

        dissimilarityPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Dissimilarity"));
        dissimilarityPanel.setLayout(new java.awt.BorderLayout());
        dissimilarityPanel.add(dissimilarityComboBox, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(dissimilarityPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void reset() {
        deltaTextField.setText(Float.toString(comp.getFractionDelta()));
        nIterationsTextField.setText(Integer.toString(comp.getNumberIterations()));
        clusterFactorTextField.setText(Float.toString(comp.getClusterFactor()));


        if (comp.getInitialization().equals(InitializationType.FASTMAP)) {
            fastmapRadioButton.setSelected(true);
            nnpRadioButton.setSelected(false);
        } else if (comp.getInitialization().equals(InitializationType.NNP)) {
            fastmapRadioButton.setSelected(false);
            nnpRadioButton.setSelected(true);
        }

        if (comp.isDistanceMatrixProvided()) {
            dissimilarityComboBox.setEnabled(false);
        } else {
            dissimilarityComboBox.setEnabled(true);
            dissimilarityComboBox.setSelectedItem(comp.getDissimilarityType());
        }
    }

    @Override
    public void finished() throws IOException {
        if (deltaTextField.getText().trim().length() > 0) {
            float delta = Float.parseFloat(deltaTextField.getText());
            if (delta > 0) {
                comp.setFractionDelta(delta);
            } else {
                throw new IOException("The fraction of delta should be positive.");
            }
        } else {
            throw new IOException("The fraction of delta should be provided.");
        }

        if (nIterationsTextField.getText().trim().length() > 0) {
            int nit = Integer.parseInt(nIterationsTextField.getText());
            if (nit > -1) {
                comp.setNumberIterations(nit);
            } else {
                throw new IOException("The number of iterations should be positive.");
            }
        } else {
            throw new IOException("The number of iterations should be provided.");
        }

        if (clusterFactorTextField.getText().trim().length() > 0) {
            float cfactor = Float.parseFloat(clusterFactorTextField.getText());
            if (cfactor > 0.0f) {
                comp.setClusterFactor(cfactor);
            } else {
                throw new IOException("The cluster factor should be positive.");
            }
        } else {
            throw new IOException("The cluster factor should be provided.");
        }

        if (this.fastmapRadioButton.isSelected()) {
            comp.setInitialization(InitializationType.FASTMAP);
        } else if (this.nnpRadioButton.isSelected()) {
            comp.setInitialization(InitializationType.NNP);
        } else {
            throw new IOException("A projector must be selected.");
        }

        if (!comp.isDistanceMatrixProvided()) {
            comp.setDissimilarityType((DissimilarityType) dissimilarityComboBox.getSelectedItem());
        }
    }

    private ProjClusProjectionComp comp;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clusterFactorLabel;
    private javax.swing.JTextField clusterFactorTextField;
    private javax.swing.JLabel deltaLabel;
    private javax.swing.JTextField deltaTextField;
    private javax.swing.JComboBox dissimilarityComboBox;
    private javax.swing.JPanel dissimilarityPanel;
    private javax.swing.JRadioButton fastmapRadioButton;
    private javax.swing.JPanel improvementPanel;
    private javax.swing.JLabel nIterationsLabel;
    private javax.swing.JTextField nIterationsTextField;
    private javax.swing.JRadioButton nnpRadioButton;
    private javax.swing.JPanel projectionPanel;
    private javax.swing.ButtonGroup projectorButtonGroup;
    // End of variables declaration//GEN-END:variables
}
