/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VisPipelineOptions.java
 *
 * Created on 30/06/2009, 11:04:35
 */
package vispipeline.view;

import javax.swing.JFrame;

/**
 *
 * @author Fernando Vieira Paulovich
 */
public class VisPipelineOptions extends javax.swing.JDialog {

    /** Creates new form VisPipelineOptions */
    private VisPipelineOptions(JFrame parent) {
        super(parent);
        initComponents();

        this.nrthreadsComboBox.setSelectedIndex(4);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        parametersPanel = new javax.swing.JPanel();
        executionPanel = new javax.swing.JPanel();
        nrthreadsComboBox = new javax.swing.JComboBox();
        nrthreadsLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tool Options");
        setModal(true);
        setResizable(false);

        parametersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameters"));
        parametersPanel.setLayout(new java.awt.GridBagLayout());

        executionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Components Execution"));
        executionPanel.setLayout(new java.awt.GridBagLayout());

        nrthreadsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        executionPanel.add(nrthreadsComboBox, gridBagConstraints);

        nrthreadsLabel.setText("Number of simultaneous threads");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        executionPanel.add(nrthreadsLabel, gridBagConstraints);

        parametersPanel.add(executionPanel, new java.awt.GridBagConstraints());

        getContentPane().add(parametersPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(closeButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    public int getNumberSimutaneousThreads() {
        return nrthreadsComboBox.getSelectedIndex() + 1;
    }

    public static VisPipelineOptions getInstance(JFrame parent) {
        if (instance == null) {
            instance = new VisPipelineOptions(parent);
        }

        return instance;
    }

    public void display() {
        instance.pack();
        instance.setLocationRelativeTo(getParent());
        instance.setVisible(true);
    }

    private static VisPipelineOptions instance;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel executionPanel;
    private javax.swing.JComboBox nrthreadsComboBox;
    private javax.swing.JLabel nrthreadsLabel;
    private javax.swing.JPanel parametersPanel;
    // End of variables declaration//GEN-END:variables
}
