/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SurfaceParam.java
 *
 * Created on Mar 28, 2010, 11:17:44 PM
 */

package projection3d.surface;

/**
 *
 * @author jpocom
 */
public class SurfaceParam extends javax.swing.JDialog {

    /** Creates new form SurfaceParam */
    public SurfaceParam(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.isoTextField.setText(""+FastDensitySurface.isovalue);
        this.radiusTextField.setText(""+FastDensitySurface.radius);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        radiusTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        isoTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Surface Paramaters"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        radiusTextField.setPreferredSize(new java.awt.Dimension(50, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel1.add(radiusTextField, gridBagConstraints);

        jLabel1.setText("Iso-value:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Radius:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        jPanel1.add(jLabel2, gridBagConstraints);

        isoTextField.setPreferredSize(new java.awt.Dimension(50, 27));
        jPanel1.add(isoTextField, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel2.add(okButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        FastDensitySurface.isovalue  = Double.parseDouble(isoTextField.getText());
        FastDensitySurface.radius  = Double.parseDouble(radiusTextField.getText());
        this.setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    public static SurfaceParam getInstance(javax.swing.JFrame parent) {
        return new SurfaceParam(parent, true);
    }


    public void display() {
        pack();
        setLocationRelativeTo(getParent());
        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField isoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField radiusTextField;
    // End of variables declaration//GEN-END:variables

}
