/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MatrixWriterParamView.java
 *
 * Created on 28/05/2009, 17:30:08
 */
package matrix.writer;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import vispipelinebasics.interfaces.AbstractParametersView;
import visualizationbasics.util.BasicsContants;
import visualizationbasics.util.SaveDialog;
import visualizationbasics.util.PropertiesManager;
import visualizationbasics.util.filter.DATAFilter;

/**
 *
 * @author Fernando Vieira Paulovich
 */
public class MatrixWriterParamView extends AbstractParametersView {

    /** Creates new form MatrixWriterParamView */
    public MatrixWriterParamView(MatrixWriterComp comp) {
        initComponents();

        this.comp = comp;
        reset();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        matrixButton = new javax.swing.JButton();
        matrixTextField = new javax.swing.JTextField();
        matrixLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Matrix Writer"));
        setLayout(new java.awt.GridBagLayout());

        matrixButton.setText("Search...");
        matrixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrixButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(matrixButton, gridBagConstraints);

        matrixTextField.setColumns(35);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(matrixTextField, gridBagConstraints);

        matrixLabel.setText("File name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(matrixLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void matrixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrixButtonActionPerformed
        try {
            PropertiesManager spm = PropertiesManager.getInstance(BasicsContants.PROPFILENAME);
            int result = SaveDialog.showSaveDialog(spm, new DATAFilter(), this, "matrix.data");
            if (result == JFileChooser.APPROVE_OPTION) {
                String filename = SaveDialog.getFilename();
                matrixTextField.setText(filename);
            }
        } catch (IOException ex) {
            Logger.getLogger(MatrixWriterParamView.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_matrixButtonActionPerformed

    @Override
    public void reset() {
        matrixTextField.setText(comp.getFilename());
    }

    @Override
    public void finished() throws IOException {
        if (matrixTextField.getText().trim().length() > 0) {
            comp.setFilename(matrixTextField.getText());
        } else {
            throw new IOException("A matrix file name must be provided.");
        }
    }

    private MatrixWriterComp comp;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton matrixButton;
    private javax.swing.JLabel matrixLabel;
    private javax.swing.JTextField matrixTextField;
    // End of variables declaration//GEN-END:variables
}
